config/routes.rb
Rails.application.routes.draw do
 get "tasks", to: "tasks#index"
 get "tasks/new", to: "tasks#new"
 get "tasks/:id", to: "tasks#show", as: "task"
 post "tasks", to: "tasks#create"
 get "tasks/:id/edit", to: "tasks#edit"
 patch "tasks/:id", to: "tasks#update"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def create
    @task = Task.new(task_params)
    @task.save

    redirect_to task_path(@task)
  end

  def new
    @task = Task.new
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @taskt.update(task_params)

    redirect_to task_path(@task)
  end

  private

  def task_params
    # *Strong params*: You need to *whitelist* what can be updated by the user
    # Never trust user data!
    params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/index.html.erb
<div class="class container">
  <h1>My tasks</h1>

    <% @tasks.each do |task| %>
      <div class="class alert-light" role="alert"><h1><%= link_to task.title, task_path(task.id)%></h1>
      </div>
      <h2><%= task.details %></h2>
          <div class="btn btn-primary"><p><%= task.completed ? "☑" : "☐" %>></p>
          </div>
        <p class="btn btn-light"><%= link_to "+ Add a new task", tasks_new_path %><% end %></p>
      </div>
</div>

app/views/tasks/new.html.erb
<div class="form-group">
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.submit %>
<% end %>
</div>

app/views/tasks/show.html.erb
<p><%= @task.details %></p>